// survey-system/src/pages/Register.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth, createUserWithEmailAndPassword } from './firebase';

const Register = ({ setUser }) => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleRegister = async (e) => {
    e.preventDefault();
    
    if (password !== confirmPassword) {
      setError('Las contraseñas no coinciden');
      return;
    }
    
    if (!email || !password || !username) {
      setError('Por favor completa todos los campos');
      return;
    }

    setIsLoading(true);
    setError('');

    try {
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      // Usuario registrado con éxito
      setUser({ 
        name: username,
        email: userCredential.user.email,
        uid: userCredential.user.uid
      });
      navigate('/dashboard');
    } catch (error) {
      console.error('Error al registrar:', error);
      setError(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h1 style={styles.title}>Regístrate</h1>
        <p style={styles.subtitle}>Crea una nueva cuenta</p>
        
        {error && <p style={styles.error}>{error}</p>}
        
        <form onSubmit={handleRegister} style={styles.form}>
          <div style={styles.inputGroup}>
            <label htmlFor="email" style={styles.label}>Correo Electrónico</label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={styles.input}
              placeholder="Ej: usuario@correo.com"
              required
            />
          </div>
          
          <div style={styles.inputGroup}>
            <label htmlFor="username" style={styles.label}>Nombre de Usuario</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              style={styles.input}
              placeholder="Ej: pepito123"
              required
            />
          </div>
          
          <div style={styles.inputGroup}>
            <label htmlFor="password" style={styles.label}>Contraseña</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={styles.input}
              placeholder="••••••••"
              required
              minLength="6"
            />
          </div>
          
          <div style={styles.inputGroup}>
            <label htmlFor="confirmPassword" style={styles.label}>Confirmar Contraseña</label>
            <input
              id="confirmPassword"
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              style={styles.input}
              placeholder="••••••••"
              required
              minLength="6"
            />
          </div>
          
          <button 
            type="submit" 
            style={styles.button}
            disabled={isLoading}
          >
            {isLoading ? (
              <span style={styles.loader}></span>
            ) : 'Registrarse'}
          </button>
        </form>
        
        <p style={styles.loginLink}>
          ¿Ya tienes una cuenta? <a href="/" style={styles.link}>Inicia sesión</a>
        </p>
      </div>
    </div>
  );
};

const styles = {
    container: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: '100vh',
      backgroundColor: '#0f0f0f',
      padding: '20px'
    },
    card: {
      width: '100%',
      maxWidth: '400px',
      backgroundColor: '#1a1a1a',
      borderRadius: '12px',
      padding: '40px',
      boxShadow: '0 8px 30px rgba(0, 0, 0, 0.3)',
      border: '1px solid #333'
    },
    title: {
      color: '#fff',
      fontSize: '28px',
      fontWeight: '600',
      marginBottom: '8px',
      textAlign: 'center'
    },
    subtitle: {
      color: '#aaa',
      fontSize: '14px',
      textAlign: 'center',
      marginBottom: '30px'
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      gap: '20px'
    },
    inputGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px'
    },
    label: {
      color: '#ddd',
      fontSize: '14px',
      fontWeight: '500'
    },
    input: {
      padding: '14px',
      borderRadius: '8px',
      border: '1px solid #333',
      backgroundColor: '#222',
      color: '#fff',
      fontSize: '15px',
      outline: 'none',
      transition: 'border 0.3s',
      ':focus': {
        borderColor: '#3a7bd5'
      }
    },
    button: {
      padding: '14px',
      borderRadius: '8px',
      border: 'none',
      backgroundColor: '#3a7bd5',
      color: 'white',
      fontSize: '16px',
      fontWeight: '600',
      cursor: 'pointer',
      marginTop: '10px',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: '46px',
      transition: 'background-color 0.3s',
      ':hover': {
        backgroundColor: '#2c5fb3'
      },
      ':disabled': {
        backgroundColor: '#2c5fb3',
        cursor: 'not-allowed'
      }
    },
    loader: {
      border: '3px solid rgba(255, 255, 255, 0.2)',
      borderTop: '3px solid white',
      borderRadius: '50%',
      width: '20px',
      height: '20px',
      animation: 'spin 1s linear infinite'
    },
    '@keyframes spin': {
      '0%': { transform: 'rotate(0deg)' },
      '100%': { transform: 'rotate(360deg)' }
    }
  };
  

export default Register;

// vue-auth-project/src/components/Register.vue
<template>
  <div class="register-container">
    <div class="register-card">
      <div class="register-header">
        <h1>Crear Cuenta</h1>
        <div class="blue-divider"></div>
      </div>

      <form @submit.prevent="register" class="register-form">
        <div class="input-group">
          <label>Nombre Completo</label>
          <input 
            v-model="name"
            type="text"
            placeholder="Tu Nombre"
            class="blue-input"
            required
          />
        </div>

        <div class="input-group">
          <label>Correo Electrónico</label>
          <input
            v-model="email"
            type="email"
            placeholder="tu@email.com"
            class="blue-input"
            required
          />
        </div>

        <div class="input-group">
          <label>Contraseña</label>
          <input
            v-model="password"
            type="password"
            placeholder="••••••••"
            class="blue-input"
            required
          />
        </div>

        <div class="input-group">
          <label>Confirmar Contraseña</label>
          <input
            v-model="confirmPassword"
            type="password"
            placeholder="••••••••"
            class="blue-input"
            required
          />
        </div>

        <div class="terms-group">
          <input 
            type="checkbox" 
            id="terms" 
            v-model="agreeTerms"
            required
          />
          <label for="terms">Acepto los términos y condiciones</label>
        </div>

        <button type="submit" class="register-button">
          Registrar Cuenta
        </button>
      </form>

      <div class="login-link">
        ¿Ya tienes cuenta? <a @click.prevent="$emit('switch-to-login')">Inicia Sesión</a>
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'

export default {
  emits: ['switch-to-login', 'register-success'],
  setup(props, { emit }) {
    const name = ref('')
    const email = ref('')
    const password = ref('')
    const confirmPassword = ref('')
    const agreeTerms = ref(false)

    const register = () => {
      if (password.value !== confirmPassword.value) {
        alert('Las contraseñas no coinciden')
        return
      }
      
      emit('register-success', {
        name: name.value,
        email: email.value
      })
    }

    return {
      name,
      email,
      password,
      confirmPassword,
      agreeTerms,
      register
    }
  }
}
</script>

<style scoped>
/* Colores principales */
:root {
  --primary-blue: #2563eb;
  --dark-blue: #1e40af;
  --light-blue: #93c5fd;
  --black: #0f172a;
  --dark-gray: #1e293b;
  --medium-gray: #334155;
  --white: #f8fafc;
}

.register-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, var(--black) 0%, var(--dark-blue) 100%);
  padding: 20px;
}

.register-card {
  width: 100%;
  max-width: 450px;
  background-color: var(--dark-gray);
  border-radius: 12px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  padding: 2.5rem;
  border: 1px solid var(--primary-blue);
}

.register-header {
  text-align: center;
  margin-bottom: 2rem;
}

.register-header h1 {
  color: var(--white);
  font-size: 2rem;
  margin-bottom: 0.5rem;
}

.blue-divider {
  height: 3px;
  background: linear-gradient(90deg, transparent, var(--primary-blue), transparent);
  margin: 0 auto;
  width: 80%;
}

.register-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.input-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.input-group label {
  color: var(--light-blue);
  font-weight: 500;
  font-size: 0.95rem;
}

.blue-input {
  padding: 12px 16px;
  background-color: rgba(255, 255, 255, 0.05);
  border: 2px solid var(--medium-gray);
  border-radius: 8px;
  color: var(--white);
  font-size: 1rem;
  transition: all 0.3s ease;
}

.blue-input:focus {
  outline: none;
  border-color: var(--primary-blue);
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.3);
  background-color: rgba(255, 255, 255, 0.1);
}

.blue-input::placeholder {
  color: rgba(255, 255, 255, 0.4);
}

.terms-group {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 1rem 0;
}

.terms-group input {
  accent-color: var(--primary-blue);
}

.terms-group label {
  color: var(--white);
  font-size: 0.9rem;
  cursor: pointer;
}

.register-button {
  padding: 14px;
  background: linear-gradient(135deg, var(--primary-blue), var(--dark-blue));
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  margin-top: 1rem;
}

.register-button:hover {
  background: linear-gradient(135deg, var(--dark-blue), var(--primary-blue));
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(37, 99, 235, 0.4);
}

.login-link {
  text-align: center;
  margin-top: 1.5rem;
  color: var(--white);
  font-size: 0.9rem;
}

.login-link a {
  color: var(--light-blue);
  text-decoration: none;
  font-weight: 500;
  cursor: pointer;
  transition: color 0.2s;
}

.login-link a:hover {
  color: var(--primary-blue);
  text-decoration: underline;
}
</style>
