// vue-auth-project/src/components/Login.vue
<template>
  <div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h2>Iniciar Sesión</h2>
        <div class="logo">
          <i class="fas fa-poll"></i>
        </div>
      </div>
      
      <form @submit.prevent="login" class="auth-form">
        <div class="input-group">
          <label for="email" class="input-label">
            <i class="fas fa-envelope"></i> Correo Electrónico
          </label>
          <input
            id="email"
            v-model="email"
            type="email"
            class="input-field"
            placeholder="tu@email.com"
            required
          />
        </div>
        
        <div class="input-group">
          <label for="password" class="input-label">
            <i class="fas fa-lock"></i> Contraseña
          </label>
          <input
            id="password"
            v-model="password"
            type="password"
            class="input-field"
            placeholder="••••••••"
            required
          />
        </div>
        
        <button type="submit" class="auth-button">
          <i class="fas fa-sign-in-alt"></i> Ingresar
        </button>
      </form>
      
      <div class="auth-footer">
        <p>¿No tienes cuenta? <a href="#" @click.prevent="$emit('switch-to-register')">Regístrate</a></p>
        <a href="#" class="forgot-password">¿Olvidaste tu contraseña?</a>
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'

export default {
  emits: ['switch-to-register', 'login-success'],
  setup(props, { emit }) {
    const email = ref('')
    const password = ref('')

    const login = () => {
      // Validación simple
      if (!email.value || !password.value) {
        alert('Por favor completa todos los campos')
        return
      }
      
      emit('login-success', email.value)
    }

    return {
      email,
      password,
      login
    }
  }
}
</script>

<style scoped>
.auth-container {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, var(--dark-blue) 0%, var(--black) 100%);
  padding: 20px;
}

.auth-card {
  width: 100%;
  max-width: 450px;
  background: var(--dark-gray);
  border-radius: 12px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
  overflow: hidden;
  border: 1px solid rgba(0, 176, 255, 0.1);
}

.auth-header {
  background: linear-gradient(90deg, var(--primary-blue), var(--light-blue));
  padding: 2rem;
  text-align: center;
  color: white;
  position: relative;
}

.auth-header h2 {
  margin: 0;
  font-size: 1.8rem;
  font-weight: 600;
}

.logo {
  position: absolute;
  top: -25px;
  right: 20px;
  background: var(--accent-blue);
  width: 50px;
  height: 50px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}

.logo i {
  font-size: 1.5rem;
}

.auth-form {
  padding: 2rem;
}

.input-group {
  margin-bottom: 1.5rem;
}

.input-label {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--accent-blue);
  font-weight: 500;
  margin-bottom: 0.5rem;
  font-size: 0.95rem;
}

.input-label i {
  font-size: 0.9rem;
}

.input-field {
  width: 100%;
  padding: 12px 15px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(0, 176, 255, 0.3);
  border-radius: 8px;
  color: white;
  font-size: 1rem;
  transition: all 0.3s ease;
}

.input-field:focus {
  outline: none;
  border-color: var(--accent-blue);
  box-shadow: 0 0 0 3px rgba(0, 176, 255, 0.2);
  background: rgba(255, 255, 255, 0.1);
}

.auth-button {
  width: 100%;
  padding: 14px;
  background: linear-gradient(90deg, var(--accent-blue), #0091ea);
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  transition: all 0.3s ease;
  margin-top: 1rem;
}

.auth-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(0, 176, 255, 0.4);
}

.auth-footer {
  padding: 0 2rem 2rem;
  text-align: center;
  font-size: 0.9rem;
  color: rgba(255, 255, 255, 0.7);
}

.auth-footer a {
  color: var(--accent-blue);
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s;
}

.auth-footer a:hover {
  color: #40c4ff;
  text-decoration: underline;
}

.forgot-password {
  display: block;
  margin-top: 0.5rem;
  font-size: 0.85rem;
}
</style>

// survey-system/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth, signInWithEmailAndPassword } from './firebase';

const Login = ({ setUser }) => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async (e) => {
    e.preventDefault();
    if (!email || !password) {
      setError('Por favor ingresa email y contraseña');
      return;
    }

    setIsLoading(true);
    setError('');

    try {
      const userCredential = await signInWithEmailAndPassword(auth, email, password);
      // Usuario autenticado con éxito
      setUser({ 
        email: userCredential.user.email,
        uid: userCredential.user.uid
      });
      navigate('/dashboard');
    } catch (error) {
      console.error('Error al iniciar sesión:', error);
      setError(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h1 style={styles.title}>Bienvenido</h1>
        <p style={styles.subtitle}>Ingresa tus credenciales</p>
        
        {error && <p style={styles.error}>{error}</p>}
        
        <form onSubmit={handleLogin} style={styles.form}>
          <div style={styles.inputGroup}>
            <label htmlFor="email" style={styles.label}>Correo Electrónico</label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={styles.input}
              placeholder="Ej: usuario@correo.com"
              required
            />
          </div>
          
          <div style={styles.inputGroup}>
            <label htmlFor="password" style={styles.label}>Contraseña</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={styles.input}
              placeholder="••••••••"
              required
            />
          </div>
          
          <button 
            type="submit" 
            style={styles.button}
            disabled={isLoading}
          >
            {isLoading ? (
              <span style={styles.loader}></span>
            ) : 'Ingresar'}
          </button>
        </form>
        
        <p style={styles.registerLink}>
          ¿No tienes una cuenta? <a href="/register" style={styles.link}>Regístrate</a>
        </p>
      </div>
    </div>
  );
};

const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#0f0f0f',
    padding: '20px'
  },
  card: {
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#1a1a1a',
    borderRadius: '12px',
    padding: '40px',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.3)',
    border: '1px solid #333'
  },
  title: {
    color: '#fff',
    fontSize: '28px',
    fontWeight: '600',
    marginBottom: '8px',
    textAlign: 'center'
  },
  subtitle: {
    color: '#aaa',
    fontSize: '14px',
    textAlign: 'center',
    marginBottom: '30px'
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px'
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px'
  },
  label: {
    color: '#ddd',
    fontSize: '14px',
    fontWeight: '500'
  },
  input: {
    padding: '14px',
    borderRadius: '8px',
    border: '1px solid #333',
    backgroundColor: '#222',
    color: '#fff',
    fontSize: '15px',
    outline: 'none',
    transition: 'border 0.3s',
    ':focus': {
      borderColor: '#3a7bd5'
    }
  },
  button: {
    padding: '14px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#3a7bd5',
    color: 'white',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '46px',
    transition: 'background-color 0.3s',
    ':hover': {
      backgroundColor: '#2c5fb3'
    },
    ':disabled': {
      backgroundColor: '#2c5fb3',
      cursor: 'not-allowed'
    }
  },
  loader: {
    border: '3px solid rgba(255, 255, 255, 0.2)',
    borderTop: '3px solid white',
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    animation: 'spin 1s linear infinite'
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' }
  },
  error: {
    color: '#ff4d4d',
    backgroundColor: 'rgba(255, 77, 77, 0.1)',
    padding: '12px',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '20px',
    textAlign: 'center'
  },
  registerLink: {
    color: '#aaa',
    fontSize: '14px',
    textAlign: 'center',
    marginTop: '20px'
  },
  link: {
    color: '#3a7bd5',
    textDecoration: 'none',
    fontWeight: '500',
    ':hover': {
      textDecoration: 'underline'
    }
  }
};

export default Login;
